package com.deqode.financeresearch.service;

import com.deqode.financeresearch.entity.Message;
import com.deqode.financeresearch.entity.Source;
import com.deqode.financeresearch.entity.Thread;
import com.deqode.financeresearch.repository.MessageRepository;
import com.deqode.financeresearch.repository.SourceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ReportExportService {
    
    @Autowired
    private MessageRepository messageRepository;
    
    @Autowired
    private SourceRepository sourceRepository;
    
    public String generateMarkdownReport(Thread thread) {
        StringBuilder markdown = new StringBuilder();
        
        // Header
        markdown.append("# Finance Research Report\n\n");
        markdown.append("**Thread:** ").append(thread.getTitle() != null ? thread.getTitle() : "Untitled Research").append("\n");
        markdown.append("**Generated:** ").append(thread.getCreatedAt().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy 'at' HH:mm"))).append("\n");
        markdown.append("**Researcher:** ").append(thread.getUser().getFullName() != null ? thread.getUser().getFullName() : thread.getUser().getEmail()).append("\n\n");
        
        markdown.append("---\n\n");
        
        // Get conversation messages
        Pageable pageable = PageRequest.of(0, 100, Sort.by("createdAt").ascending());
        Page<Message> messagePage = messageRepository.findMessagesByThread(thread, pageable);
        List<Message> messages = messagePage.getContent();
        
        // Extract research query and AI responses
        String researchQuery = null;
        StringBuilder analysis = new StringBuilder();
        
        for (Message message : messages) {
            if (message.getRole() == Message.MessageRole.USER && researchQuery == null) {
                researchQuery = message.getContent();
            } else if (message.getRole() == Message.MessageRole.ASSISTANT) {
                analysis.append(message.getContent()).append("\n\n");
            }
        }
        
        // Research Question
        if (researchQuery != null) {
            markdown.append("## 🔍 Research Question\n\n");
            markdown.append(researchQuery).append("\n\n");
        }
        
        // Analysis Section
        if (analysis.length() > 0) {
            markdown.append("## 📊 Financial Analysis\n\n");
            markdown.append(analysis.toString());
        }
        
        // Sources Section
        List<Source> sources = sourceRepository.findRelevantSourcesByThread(thread);
        if (!sources.isEmpty()) {
            markdown.append("## 📚 Research Sources\n\n");
            
            int sourceNum = 1;
            for (Source source : sources) {
                markdown.append("### [").append(sourceNum).append("] ").append(source.getTitle() != null ? source.getTitle() : "Source").append("\n\n");
                markdown.append("**URL:** [").append(source.getUrl()).append("](").append(source.getUrl()).append(")\n");
                markdown.append("**Domain:** ").append(source.getDomain()).append("\n");
                if (source.getRelevanceScore() != null) {
                    markdown.append("**Relevance Score:** ").append(String.format("%.1f/10", source.getRelevanceScore().floatValue() * 10)).append("\n");
                }
                if (source.getSnippet() != null) {
                    markdown.append("**Summary:** ").append(source.getSnippet()).append("\n");
                }
                markdown.append("\n");
                sourceNum++;
            }
        }
        
        // Footer
        markdown.append("---\n\n");
        markdown.append("*This report was generated by the Finance Research Chatbot. Please verify all information with official sources before making investment decisions.*\n\n");
        markdown.append("*Report generated on ").append(java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy 'at' HH:mm"))).append("*\n");
        
        return markdown.toString();
    }
    
    public String generateHtmlReport(Thread thread) {
        StringBuilder html = new StringBuilder();
        
        // HTML Header
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"en\">\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("    <title>Finance Research Report</title>\n");
        html.append("    <style>\n");
        html.append("        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; margin: 0; padding: 40px; background-color: #f5f5f5; }\n");
        html.append("        .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\n");
        html.append("        h1 { color: #1976d2; border-bottom: 3px solid #1976d2; padding-bottom: 10px; }\n");
        html.append("        h2 { color: #424242; border-left: 4px solid #1976d2; padding-left: 15px; }\n");
        html.append("        h3 { color: #666; }\n");
        html.append("        .meta { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }\n");
        html.append("        .source { background-color: #fff; border: 1px solid #ddd; padding: 15px; margin: 10px 0; border-radius: 5px; }\n");
        html.append("        .source-title { font-weight: bold; color: #1976d2; }\n");
        html.append("        .source-url { word-break: break-all; }\n");
        html.append("        .badge { background-color: #1976d2; color: white; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; }\n");
        html.append("        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-style: italic; }\n");
        html.append("        strong { color: #1976d2; }\n");
        html.append("        a { color: #1976d2; text-decoration: none; }\n");
        html.append("        a:hover { text-decoration: underline; }\n");
        html.append("    </style>\n");
        html.append("</head>\n");
        html.append("<body>\n");
        html.append("    <div class=\"container\">\n");
        
        // Title and metadata
        html.append("        <h1>🏦 Finance Research Report</h1>\n");
        html.append("        <div class=\"meta\">\n");
        html.append("            <strong>Thread:</strong> ").append(htmlEscape(thread.getTitle() != null ? thread.getTitle() : "Untitled Research")).append("<br>\n");
        html.append("            <strong>Generated:</strong> ").append(thread.getCreatedAt().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy 'at' HH:mm"))).append("<br>\n");
        html.append("            <strong>Researcher:</strong> ").append(htmlEscape(thread.getUser().getFullName() != null ? thread.getUser().getFullName() : thread.getUser().getEmail())).append("\n");
        html.append("        </div>\n");
        
        // Get conversation messages
        Pageable pageable2 = PageRequest.of(0, 100, Sort.by("createdAt").ascending());
        Page<Message> messagePage2 = messageRepository.findMessagesByThread(thread, pageable2);
        List<Message> messages = messagePage2.getContent();
        
        // Extract research query and AI responses
        String researchQuery = null;
        StringBuilder analysis = new StringBuilder();
        
        for (Message message : messages) {
            if (message.getRole() == Message.MessageRole.USER && researchQuery == null) {
                researchQuery = message.getContent();
            } else if (message.getRole() == Message.MessageRole.ASSISTANT) {
                analysis.append(markdownToHtml(message.getContent())).append("\n");
            }
        }
        
        // Research Question
        if (researchQuery != null) {
            html.append("        <h2>🔍 Research Question</h2>\n");
            html.append("        <p>").append(htmlEscape(researchQuery)).append("</p>\n");
        }
        
        // Analysis Section
        if (analysis.length() > 0) {
            html.append("        <h2>📊 Financial Analysis</h2>\n");
            html.append("        <div>").append(analysis.toString()).append("</div>\n");
        }
        
        // Sources Section
        List<Source> sources = sourceRepository.findRelevantSourcesByThread(thread);
        if (!sources.isEmpty()) {
            html.append("        <h2>📚 Research Sources</h2>\n");
            
            int sourceNum = 1;
            for (Source source : sources) {
                html.append("        <div class=\"source\">\n");
                html.append("            <div class=\"source-title\">[").append(sourceNum).append("] ").append(htmlEscape(source.getTitle() != null ? source.getTitle() : "Source")).append("</div>\n");
                html.append("            <div class=\"source-url\"><strong>URL:</strong> <a href=\"").append(htmlEscape(source.getUrl())).append("\" target=\"_blank\">").append(htmlEscape(source.getUrl())).append("</a></div>\n");
                html.append("            <div><strong>Domain:</strong> <span class=\"badge\">").append(htmlEscape(source.getDomain())).append("</span></div>\n");
                if (source.getRelevanceScore() != null) {
                    html.append("            <div><strong>Relevance Score:</strong> ").append(String.format("%.1f/10", source.getRelevanceScore().floatValue() * 10)).append("</div>\n");
                }
                if (source.getSnippet() != null) {
                    html.append("            <div><strong>Summary:</strong> ").append(htmlEscape(source.getSnippet())).append("</div>\n");
                }
                html.append("        </div>\n");
                sourceNum++;
            }
        }
        
        // Footer
        html.append("        <div class=\"footer\">\n");
        html.append("            <p>This report was generated by the Finance Research Chatbot.<br>\n");
        html.append("            Please verify all information with official sources before making investment decisions.</p>\n");
        html.append("            <p>Report generated on ").append(java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy 'at' HH:mm"))).append("</p>\n");
        html.append("        </div>\n");
        html.append("    </div>\n");
        html.append("</body>\n");
        html.append("</html>");
        
        return html.toString();
    }
    
    private String htmlEscape(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("\"", "&quot;")
                  .replace("'", "&#39;");
    }
    
    private String markdownToHtml(String markdown) {
        if (markdown == null) return "";
        
        // Simple markdown to HTML conversion
        String html = markdown;
        
        // Bold text
        html = html.replaceAll("\\*\\*(.*?)\\*\\*", "<strong>$1</strong>");
        
        // Headers
        html = html.replaceAll("## (.*?)\n", "<h3>$1</h3>\n");
        html = html.replaceAll("# (.*?)\n", "<h2>$1</h2>\n");
        
        // Bullet points
        html = html.replaceAll("• (.*?)\n", "<li>$1</li>\n");
        html = html.replaceAll("(<li>.*?</li>\n)+", "<ul>$0</ul>");
        
        // Line breaks
        html = html.replace("\n", "<br>\n");
        
        return html;
    }
}